name: Snyk Security Scan

on:
  push:
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4. Run Snyk scan
      - name: Run Snyk scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. Build + SonarCloud Scan
      - name: Build and Analyze with SonarCloud
        run: |
          mvn -B verify sonar:sonar 
            -Dsonar.projectKey=java-reachability-playground-hunt 
            -Dsonar.organization=java-reachability-playground-hunt 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.login=$SONAR_TOKEN

        continue-on-error: true
