name: Snyk Security Scan

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build + SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar
          -Dsonar.projectKey=java-reachability-playground-hunt
          -Dsonar.organization=java-reachability-playground-hunt
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${SONAR_TOKEN}

      - name: Run Snyk Scan
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
